src/ST/AdminBundle/Form/FigureHistoRestoreType.php
<?php

namespace ST\AdminBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Ivory\CKEditorBundle\Form\Type\CKEditorType;
use ST\FigureBundle\Entity\FigureHisto;


class FigureHistoRestoreType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
		$resolver->setDefaults(array(
            'data_class' => FigureHisto::class,
        ));
    }

	
	public function getName() {
		return 'standalone';
	}


}

src/ST/AdminBundle/Controller/AdminController.php
<?php

namespace ST\AdminBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;

use ST\AdminBundle\Form\FigureHistoRestoreType;

class AdminController extends Controller
{
    public function indexAction()
    {
    	return $this->render('STAdminBundle:Default:index.html.twig',
            array(
                'figures' => $this->get('admin_service')->getFigures()
            ));
    }
    
    public function activateAction($id, $actValue)
    {
    	$this->get('admin_service')->setActive($id, $actValue);
    	return $this->redirectToRoute('st_admin_homepage');
    	
    }
    
    public function histoAction($id)
    {
    	return $this->render('STAdminBundle:Default:histo.html.twig',
            array(
                'histo' => $this->get('admin_service')->getHisto($id)));
    }
    
    public function viewAction($id,$version, Request $request)
    {
        $figureHisto = $this->get('admin_service')->getVersion($version);
		$form = $this->get('form.factory')
            ->create(FigureHistoRestoreType::class, $figureHisto);
		
		if ($request->isMethod('POST') && $form->handleRequest($request)->isValid())
		{
			$this->get('admin_service')->restoreFigure($figureHisto);			
			return $this->redirectToRoute('st_home');
		}
        return $this->render('STAdminBundle:Default:restore.html.twig', array(
								'figure' => $figureHisto,
								'form' => $form->createView(),
    							));
    }
}

src/ST/AdminBundle/Controller/DefaultController.php
<?php

namespace ST\AdminBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class DefaultController extends Controller
{
    public function indexAction()
    {
        return $this->render('STAdminBundle:Default:index.html.twig');
    }
}

src/ST/AdminBundle/Tests/Controller/DefaultControllerTest.php
<?php

namespace ST\AdminBundle\Tests\Controller;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class DefaultControllerTest extends WebTestCase
{
    public function testIndex()
    {
        $client = static::createClient();

        $crawler = $client->request('GET', '/');

        $this->assertContains('Hello World', $client->getResponse()->getContent());
    }
}

src/ST/AdminBundle/Resources/views/Default/histo.html.twig
{% extends "STAdminBundle::layout.html.twig" %}

{% block admin %}
    <div class="container">
      <h2>Historique de la page : </h2>
      <ul class="list-group">
      	{% for version in histo %}
        	<li class="list-group-item">
        		{{ version.name}} posted by {{ version.user.username}} on {{ version.updateDateHisto |date("d/m/y H:i:s") }}
        		<span class = 'pull-right pull-right-margin'><a href = "{{ path('st_admin_view', {'id': version.idfigure, 'version': version.id}) }}">Restore</a></span>
         {% endfor %}
        
      </ul>
    </div>
{% endblock %}

src/ST/AdminBundle/Resources/views/Default/index.html.twig
{% extends "STAdminBundle::layout.html.twig" %}

{% block admin %}
    <div class="container">
      <h2>Listes des différentes pages :</h2>
      <ul class="list-group">
      	{% for figure in figures %}
        	<li class="list-group-item">
        		{{ figure.name }}
        		<span class = 'pull-right pull-right-margin'><a href = "{{ path('st_admin_histo', {'id': figure.id}) }}">historique</a></span>
        		{% if figure.active == 0 %}
        			<span class = 'pull-right pull-right-margin'><a href = "{{ path('st_admin_activate', {'id': figure.id, 'actValue' : 1}) }}">désactiver</a></span></li>
        		{% else %}
					<span class = 'pull-right pull-right-margin'><a href = "{{ path('st_admin_activate', {'id': figure.id, 'actValue' : 0}) }}">ré-activer</a></span></li>
				{% endif %}        
         {% endfor %}
        
      </ul>
    </div>
{% endblock %}

src/ST/AdminBundle/Resources/views/Default/restore.html.twig
{% extends "STAdminBundle::layout.html.twig" %}

{% block admin %}
<section id="myFigure">
        <div class="container">
			<div class="col-lg-10 col-lg-offset-1">
				<div class="row">
					<h2>{{ figure.name }}</h2>
					Posted by <i>{{ figure.user.username }}</i> on {{ figure.updateDate|date("d/m/y") }}
					<p> {{ figure.description|raw }}</p>
					
				</div>
            
				{% if is_granted("ROLE_ADMIN") %}
				
				{{ form_start(form) }}					
				<div class="row">
					<hr>
					<div class="text-right">
						<button type="submit" class="btnsave btn btn-default">Restore</button>
					</div>
				</div>
				{{ form_end(form) }}
				{% endif %}
        </div>
    </section>
  

{% endblock %}

src/ST/AdminBundle/Resources/views/layout.html.twig

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Snow Tricks{% endblock %}</title>

    {% block stylesheets %}
      {# On charge le CSS de bootstrap depuis le site directement #}
      <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		<link href="{{ asset('css/snow_tricks.css') }}" rel="stylesheet">
	   <!-- Custom Fonts -->
		<link href="{{ asset('vendor/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet" type="text/css">
		<link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
		<link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    {% endblock %}
  </head>

  <body>
	  <nav  class="navbar navbar-default navbar-fixed-top">
  			<div class="container-fluid">
				<div class="navbar-header page-scroll">
					<a class="navbar-brand" href="{{ path('st_home') }}">Home</a>
				</div>
				<ul class="nav navbar-nav navbar-right">
					{% if is_granted("ROLE_USER") %}
						<li><a href="#"><span class="glyphicon glyphicon-user"></span>{{ app.user.username }}</a> </li>
						<li><a href="{{ path('st_logout') }}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
					{% endif %}
				</ul>
  			</div>
		</nav>
	   <header  class="intro-header">
        <div class="container">
            <div class="row">
            </div>
        </div>
    </header>
	  
	{% block admin %}{% endblock %}
	

  {% block javascripts %}
    {# Ajoutez ces lignes JavaScript si vous comptez vous servir des fonctionnalités du bootstrap Twitter #}
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

	
    <!-- Theme JavaScript -->
    <script src="{{ asset('js/clean-blog.min.js') }}"></script>
  {% endblock %}

  </body>
</html>
